# Generated by Django 3.2.9 on 2021-12-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='draft', max_length=10),
        ),
    ]
