# Generated by Django 3.2.9 on 2021-11-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("confirmed", "confirmed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
