# Generated by Django 3.2.9 on 2021-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("cancelled", "cancelled"), ("active", "active")],
                default="active",
                max_length=10,
            ),
        ),
    ]
