# Generated by Django 3.2.9 on 2021-11-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[("available", "available"), ("confirmed", "confirmed")],
                default="available",
                max_length=10,
            ),
        ),
    ]
