# Generated by Django 3.2.8 on 2021-10-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="reg_date",
        ),
    ]
