# Generated by Django 3.2.9 on 2021-11-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], default='active', max_length=10),
        ),
    ]
