# Generated by Django 3.2.10 on 2021-12-14 14:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2021, 12, 14)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.time(9, 19, 13, 418142)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("expired", "expired"),
                    ("cancelled", "cancelled"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
