# Generated by Django 3.2.8 on 2021-12-11 01:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20211208_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2021, 12, 10))]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.time(20, 17, 6, 543028))]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('active', 'active'), ('expired', 'expired')], default='active', max_length=10),
        ),
    ]
