# Generated by Django 3.2.8 on 2021-11-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('confirmed', 'confirmed')], default='available', max_length=10),
        ),
    ]
