# Generated by Django 3.2.9 on 2021-12-08 19:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20211208_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.time(14, 24, 23, 396480))]),
        ),
    ]
