# Generated by Django 3.2.9 on 2021-12-08 20:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_appointment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2021, 12, 8))]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.time(15, 23, 48, 319377))]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='active', max_length=10),
        ),
    ]
