# Generated by Django 3.2.8 on 2021-11-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_appointments_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[("available", "available"), ("confirmed", "confirmed")],
                default="available",
                max_length=10,
            ),
        ),
    ]
