# Generated by Django 3.2.8 on 2021-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_provider_timeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('available', 'available')], default='available', max_length=10),
        ),
    ]
