# Generated by Django 3.2.7 on 2021-10-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmental', '0002_auto_20211024_2249'),
        ('vmental', '0008_alter_customizeduser_gender'),
    ]

    operations = [
    ]
