# Generated by Django 3.2.8 on 2021-10-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmental', '0002_auto_20211026_1847'),
        ('vmental', '0008_alter_customizeduser_gender'),
    ]

    operations = [
    ]
