# Generated by Django 3.2.8 on 2021-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmental", "0011_alter_customizeduser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customizeduser",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
# Generated by Django 3.2.8 on 2021-10-27 20:25
